### ISSUE TITLE
Nombre Proyecto sobre 150 caracteres con modificaciones

### ISSUE THREAD

**Issue by danteghirardelli** [InstitutoNacionalDeDeportes/SolictudDeCambio#15]
## Nombre Proyecto

weuryeworywoeryewryweyrewyrweuyroweytrwuyetruweytrweuyrtweyurtgweuyrgweyurgewyrgweuyrgweuyrgweuyrgweuygruywguwyerguywegruweyrweyugruwqeygrwuqewue1234567
(152 caracteres)

![image](https://cloud.githubusercontent.com/assets/21196249/26318347/d5fcbc4c-3ee8-11e7-93b6-59a6cbb02e1a.png)
![image](https://cloud.githubusercontent.com/assets/21196249/26318352/d9f43154-3ee8-11e7-9ae6-fa327fd8fadc.png)

![image](https://cloud.githubusercontent.com/assets/21196249/26318358/de25238c-3ee8-11e7-8256-052707477202.png)

Al grabar solo permite 150 caracteres.

![image](https://cloud.githubusercontent.com/assets/21196249/26318374/e92a3650-3ee8-11e7-91f4-b87a9377cf28.png)

## Campos Fin, Estado y Acción quedan fuera de foco cuando el Nombre del Proyecto tiene 150 caracteres

![image](https://cloud.githubusercontent.com/assets/21196249/26318414/04ebe12c-3ee9-11e7-957f-d580c8e735b8.png)
Editar Nombre
![image](https://cloud.githubusercontent.com/assets/21196249/26318428/0ee55da2-3ee9-11e7-8407-3180e31918be.png)

![image](https://cloud.githubusercontent.com/assets/21196249/26318438/13245652-3ee9-11e7-95b6-9916981a1508.png)
Guardar Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/26318450/1e38a552-3ee9-11e7-946e-999cdb900e1f.png)

No modifica el Nombre automáticamente (refresh automático).

Se carga nuevamente la Bandeja de Proyectos y se consulta el Cambio Proyecto “Modificar Nombre 98765"
![image](https://cloud.githubusercontent.com/assets/21196249/26318498/520a4a7a-3ee9-11e7-8a2a-03b8a919287b.png)

## Nueva Modificación al Nombre de Proyecto
![image](https://cloud.githubusercontent.com/assets/21196249/26318516/61914d90-3ee9-11e7-8dab-c6ca4b26adf0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/26318521/65d693f6-3ee9-11e7-9a10-f7ddece25ac3.png)

## Se ingresan nuevos caracteres en el Nombre de Proyecto
![image](https://cloud.githubusercontent.com/assets/21196249/26318547/8257566e-3ee9-11e7-95c5-5ae242d1ddbe.png)
No se actualiza automáticamente el cambio.
## Se debe ir a Bandeja de Entrada para ver los cambios
![image](https://cloud.githubusercontent.com/assets/21196249/26318568/922e72c0-3ee9-11e7-8e86-bea1d4549a90.png)

## Resumen
- Sistema no permite un Nombre de Proyecto con mas de 150 caracteres
- Al ingresar un Nombre de Proyecto de 150 caracteres los campos Campos Fin, Estado y Acción quedan fuera de foco .
- No modifica el Nombre automáticamente (refresh).
- Se carga nuevamente la Bandeja de Proyectos y se consulta el Cambio Proyecto “Modificar Nombre 98765"
- Al ir a la Bandeja de Proyectos se muestran los cambios.

@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
# Conclusión:

**Esto fue solucionado.**
