### ISSUE TITLE
Proyectos Aprobados

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#19]
Se deberán crear las versiones de los proyectos en estado aprobado correspondientes al año 2017.

Los de color Verde: GATO, Azul: YO , Pablo: Amarillo.

**Comment by felipedonoso** [comment]
El archivo es el siguiente:

[CrearVersiónProyecto.xlsx](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/1022871/CrearVersionProyecto.xlsx)

La URL es la siguiente: El parámetro a cambiar es el IDproyecto

http://www.proyectosdeportivos.cl/AltoRendimiento/IndReportes/Default.aspx?idreporte=1&idproyecto=**613**&creaPdf=true

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Versiones creadas.

Adjunto archivo.

Si tienen alguna consulta me dicen.
[CrearVersionProyecto_GATO.xlsx](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/1023078/CrearVersionProyecto_GATO.xlsx)

**Comment by felipedonoso** [comment]
La tarea se da por terminada, ya que todos los proyectos aprobados del concurso 2017 están en estado APROBADO.

Solamente los proyectos con más de una versión, corresponden a pruebas del Departamento de informática del IND.

![image](https://cloud.githubusercontent.com/assets/5757157/26411512/0c87e908-4074-11e7-9c34-4a58dd592c00.png)


# Conclusión:

**A terminado con éxito.**
