### ISSUE TITLE
Iconos de Versionamiento, en los perfiles

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#26]
@pabloespinoza, habría que actualizar los iconos para todos los perfiles la verdad, ya que la mayoría a excepto de Finanzas lo necesitará con urgencia.

![image](https://user-images.githubusercontent.com/5757157/28378684-0543d1f2-6c7f-11e7-85e4-012ac789d44b.png)

Los iconos que debería aparecer:

![image](https://user-images.githubusercontent.com/5757157/28378785-72f0118e-6c7f-11e7-88f5-2e6850e2b288.png)

![image](https://user-images.githubusercontent.com/5757157/28378913-e761159a-6c7f-11e7-858d-d3ee5e390318.png)

De faltar alguno favor de indicármelo.

**Comment by pabloespinoza** [comment]
Se realizan los siguientes cambios de permisos en AdministracionQA

**1	POSTULANTE**
**2	ANALISTA:** Boton Historial de Solicitud de Cambio (Bandeja de Proyecto), BOTÓN HISTORIAL DE CAMBIOS - BANDEJA PROYECTOS
**3	ANALISTA/PRESUPUESTO:** Boton Historial de Solicitud de Cambio (Bandeja de Proyecto), BOTÓN HISTORIAL DE CAMBIOS - BANDEJA PROYECTOS
**4	JEFATURA:** Boton Historial de Solicitud de Cambio (Bandeja de Proyecto), BOTÓN HISTORIAL DE CAMBIOS - BANDEJA PROYECTOS
**5	FINANZAS:** evaluacion preseleccionado, evaluacion seleccionada, evaluar postulados, evaluar preseleccionado, evaluar seleccionado, ver proyecto (volver proyecto atras), solicitud de cambio
**6	FIZCALIZADOR:**  evaluacion preseleccionado, evaluacion seleccionada, evaluar postulados, evaluar preseleccionado, evaluar seleccionado, ver proyecto (volver proyecto atras), solicitud de cambio
**9	ADMINISTRADOR**
**13	Super Usuario**

**Comment by felipedonoso** [comment]
@pabloespinoza, como me mencionaste en producción se encuentra el mantenedor de permisos:

![image](https://user-images.githubusercontent.com/5757157/28421024-f4ce460a-6d31-11e7-85e4-438e58e8e52a.png)

Se revisa en PRODUCCIÓN: Se utiliza mi rut: 15736232.

![image](https://user-images.githubusercontent.com/5757157/28425181-86450f32-6d3d-11e7-97a2-65f728227048.png)

Después de Actualizar los permisos en producción: Se mantiene los caracteres en la sección **Acción**:

![image](https://user-images.githubusercontent.com/5757157/28425734-2e33c318-6d3f-11e7-93ad-3aaa68f63d11.png)

**Comment by felipedonoso** [comment]
Se avanzará el proyecto "PRUEBA APOYO ESPECIAL DEPORTISTA FECHA DE TERMINO", hasta al enviar una SC:

EDITE EL NOMBRE DEL PROYECTO: **PRUEBA DE INFORMÁTICA PERFILES- FAVOR DE OMITIR**

**Nota: no se obtiene el mes de INICIO:**

![image](https://user-images.githubusercontent.com/5757157/28425957-c4cf1aa2-6d3f-11e7-8769-eeb690179966.png)

Se vuelve a postular un proyecto:

![image](https://user-images.githubusercontent.com/5757157/28426337-d4575628-6d40-11e7-85b8-b5c3e8048471.png)


# Conclusiones:

**@pabloespinoza habría que replicar estos perfiles a producción estaría todo OK.**
