### ISSUE TITLE
Conclusiones SC

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#3]
### Acá se hace un resumen de los resultados de las tareas de revisión de la solicitud de cambio:

1. Al crear el gasto en personal, se puede apreciar que no aparece la opción de agregar beneficiario, solicitado por Daniela, en los gastos de **Bienes y Servicios.**
2. No se puede revisar una SC, el sistema de administración solo presenta la opción de ver documentos.

### Por prioridad el más importante sería el punto 2, ya que no permite la revisión en la parte de Administración.

Para obtener mayor información de los errores se adjuntan las tareas asociadas a dicho error:

1. https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/2
2. https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/5

**Comment by pabloespinoza** [comment]
@felipedonoso Ya esta habilitada la opción para poder realizar la revisión de la solicitud de cambio, había que descomentar la opción.

**Comment by felipedonoso** [comment]
Al revisar se aprecia los iconos:

![image](https://cloud.githubusercontent.com/assets/5757157/24360392/9bd91682-12dd-11e7-9cd4-1cd80d80bd27.png)

Se aprecia que el icono de SC, esta encima de los otros, habría que ver la posibilidad de listarlos en orden horizontal.
![image](https://cloud.githubusercontent.com/assets/5757157/24360480/cae3e7d6-12dd-11e7-96e6-5343c045f384.png)

Al presionar el icono de la SC, aparece un error:
![image](https://cloud.githubusercontent.com/assets/5757157/24360646/4814d3b4-12de-11e7-8ff7-018402321248.png)

**Comment by pabloespinoza** [comment]
@felipedonoso el error aparece por que el sitio del web service de Converges donde esta apuntando QA se esta bajando, procederé a cambiar la url al sitio correcto.

**Comment by felipedonoso** [comment]
### Errores detectados en la tarea : https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/6

Cambio de ejecución: Modificar la fecha de termino del producto, a un mes anterior al que ya presenta.

1. No fue posible modificar la fecha de termino del producto.
2. El campo categoría al momento de presionar guardar no se visualiza lo que selecciono el usuario.

**Comment by pabloespinoza** [comment]
@felipedonoso Se modifica url del reporte, ahora queda de forma dinámica tomando la url del web.config y se alinean los iconos de acción de los proyectos.

![image](https://cloud.githubusercontent.com/assets/21196998/24377344/7d45fc8e-1315-11e7-9109-3ee4efad307a.png)

**Comment by felipedonoso** [comment]
Este es el error @pabloespinoza 👍 

Al revisar el reporte no es posible visualizarlo ni descargarlo:

![image](https://cloud.githubusercontent.com/assets/5757157/24410001/43e30e94-13a8-11e7-8464-540e1bfd1e35.png)

**Comment by pabloespinoza** [comment]
@felipedonoso ya puedes probar nuevamente.

**Comment by felipedonoso** [comment]
@pabloespinoza como lo conversamos, habría que comentar la línea que valida que no se permita poder modificar la fecha fin de un producto a un mes anterior al que postularon.

Lo otro, al ver el reporte creo que esta mostrando la versión antigua y no el aprobado por la SC, para mayor información esta en la tarea: https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/5

**Comment by felipedonoso** [comment]
@pabloespinoza, se encontraron problemas en el reporte al momento de comparar el proyecto antes de la SC y después de la SC.

Proyecto antes de SC:
[Proyecto1700042021_AntesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/893128/Proyecto1700042021_AntesSC.pdf)

Proyecto después de SC.
[Proyecto1700042021_DespuesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/893134/Proyecto1700042021_DespuesSC.pdf)


Para mayor información ver los comentarios en la tarea: https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/4#issuecomment-291238572

**Comment by felipedonoso** [comment]
@pabloespinoza, como lo habíamos conversado ayer, sería agregar los campos del formulario del producto, ya que si la federación solamente desea modificar el lugar del mismo como región y comuna estos no se pueden visualizar.

![image](https://cloud.githubusercontent.com/assets/5757157/25533069/be60f8d2-2c05-11e7-980e-e71e6d53dac8.png)

**Comment by felipedonoso** [comment]
@pabloespinoza otro problema mas simple a corregir es el siguiente:

1. Correo electrónico, al momento de enviar la SC, no debe decir SC aprobada, sino **Enviada.**

Para mayor información:
https://github.com/danteghirardelli/Pruebas-SC/issues/6

**Comment by felipedonoso** [comment]
@pabloespinoza No se puede apreciar las versiones del proyecto.

Esto debería verse cualquiera sea el estado, de no haber información ver si se despliega sin errores indicando que no hay información o que diga null.

Para mayor información:
https://github.com/danteghirardelli/Pruebas-SC/issues/8

**Comment by felipedonoso** [comment]
@pabloespinoza, hay un problema al revisar el reporte original en el campo Cargo:

![image](https://cloud.githubusercontent.com/assets/5757157/25676108/3ca2148c-3017-11e7-9acd-afe701093bb0.png)

Para mayor información: https://github.com/danteghirardelli/Pruebas-SC/issues/4

**Comment by felipedonoso** [comment]
@pabloespinoza , como te lo había comentado estos son los problemas detectados:

1. Dejar un tamaño máximo de archivo de 50 MB. Claro si lo puede soportar, de no ser así 25 MB.
2. De indicar un error por el tamaño de archivo, indicar el máximo  soportado.
3. También en lo posible si se puede ver el tema de la sesión, redireccionar al login.
4. Separadores de miles en los campos que se ingresan montos Postulación.
5. Reporte en visualización y al exportar a EXCEL.

Los puntos 1 y 2, son los más urgentes para el paso a producción los otros pueden esperar.

Para mayor información del error detectado se encuentra en la tarea:
https://github.com/danteghirardelli/Pruebas-SC/issues/10

**Comment by felipedonoso** [comment]
@pabloespinoza no se puede apreciar el icono de SC: **1700042025**

Este proyecto se envío la SC y mostró ERROR al procesar la solicitud. Para mayor información:

https://github.com/danteghirardelli/Pruebas-SC/issues/10

**Comment by felipedonoso** [comment]
@pabloespinoza se encontro un problema al revisar el cambio de Región en un producto:

Cambios al producto:

Región: Metropolitana => **Tarapacá**
Comuna: Santiago => **Huara**

Región: El cambio de región no se aprecia, dice **_Nacional_** para ambos casos:

![image](https://cloud.githubusercontent.com/assets/5757157/25808145/8b8dfc5c-33df-11e7-997c-b9e24b110ee0.png)

Esto corresponde a la tarea: https://github.com/danteghirardelli/Pruebas-SC/issues/7

**Comment by felipedonoso** [comment]
@pabloespinoza al entrar a las 09:00 HRS. Esto corresponde al día de ayer 15 de mayo 2017.

 Aparece No es posible acceder a la plataforma:
![image](https://cloud.githubusercontent.com/assets/5757157/26058668/d8f6be1c-394c-11e7-87ba-91aef94fa328.png)

Como también lo mencionado ayer sobre el error al consultar la barra de "**Rendiciones pendientes en postulación".**

**Comment by felipedonoso** [comment]
@pabloespinoza como lo hablamos ayer, se encontró que en el historial de cambios, no queda registro al momento de aprobar la SC, en la tabla: **_observaciones_proyecto_**:

![image](https://cloud.githubusercontent.com/assets/5757157/26175017/3a0868ee-3b1f-11e7-834d-295934a143f8.png)

También,  ver al momento de rechazar una SC, que vuelva a dejarlo en estado Aprobado.

**Comment by felipedonoso** [comment]
@pabloespinoza 

1. El histórico de estados esta OK, para pasar a producción.
2. Sesión Administración OK.
3. Histórico de estados OK.
4. Modificar producto OK.
5. Modificar proyecto Ok


Favor de dejar el código necesario para pasar a producción.

**Comment by felipedonoso** [comment]
Revisando estado Incompleto:

![image](https://cloud.githubusercontent.com/assets/5757157/26419854/fb5922ee-408e-11e7-879e-8c05563f3b45.png)

Al editarlo:

![image](https://cloud.githubusercontent.com/assets/5757157/26419883/105ef5a6-408f-11e7-9507-155e563e1fe7.png)

El mes de termino aparece Bloqueado y es un proyecto de la linea PDE planes de desarrollo estratégico. Esto es valido solo para los proyectos de la linea PDA : **_Art.  1º Ley 19135...._**

Debería quedar el mes habilitado el de termino para las lineas distintas al PDA.

**Comment by felipedonoso** [comment]
@pabloespinoza favor de pasar a producción saludos.

**Comment by felipedonoso** [comment]
@pabloespinoza, al revisar el proyecto en estado "INGRESADO", se pudo modificar sin problemas, el tema ocurre cuando el proyecto una vez se acepta por parte del ANALISTA, y se vuelve a postular y posteriormente se OBJETA, el sistema debería seguir el flujo normal y que permita poder volver postularlo:

**_El código: 1700042038
Nombre: CambioCargo_050517_**

**Comment by felipedonoso** [comment]
Modificar el correo de SC al momento de enviar y aprobar sc:

Mayor detalle:  Debería mejorar el correo enviado de aprobación indicando el número real de la SC aprobada que sería 1 e indicar el nombre del proyecto / código - nombre del producto.

https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/22

**Comment by felipedonoso** [comment]
@pabloespinoza esto ocurre al momento de crear una nueva SC: Proyecto 1700042001

Solo se pincho el icono:

![image](https://user-images.githubusercontent.com/5757157/26888014-c1ea4134-4b77-11e7-9e38-aa0a8a7ade0a.png)

Me avisas, estoy utilizando este proyecto para hacer la prueba del Email.

**Comment by felipedonoso** [comment]
@pabloespinoza, realice las pruebas del correo electrónico cuando se envía una SC, y no llego al correo de Hotmail y el de gmail no sirve ya que no hay espacio disponible, también se reviso el correo de analista de la lista Liderazgo y tampoco.

El detalle de la prueba se encuentra en:

https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/issues/46

**Comment by felipedonoso** [comment]
Lo anterior ya fue solucionado y revisado en la tarea:
https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/issues/46

**Comment by felipedonoso** [comment]
@pabloespinoza como lo conversamos ayer , con respecto al problema del reporte de un **proyecto que esta aprobado con Solicitud de cambio en revisión**, lo ideal sería que se pueda descargar el reporte de la última versión.

Para mayor información, se encuentra en la tarea:

https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/23

**Comment by felipedonoso** [comment]
@pabloespinoza, esta es la tarea para el tema de la GRILLA:

https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/25

**Comment by felipedonoso** [comment]
Revisando el reporte del proyecto de la SC:

Se utilizará el siguiente código: **1700042021**

![image](https://user-images.githubusercontent.com/5757157/28026458-20e13886-6564-11e7-99ee-6b8cea5f4bad.png)

Datos del producto:
![image](https://user-images.githubusercontent.com/5757157/28026488-38d56980-6564-11e7-8933-69e5f202af7d.png)

Se modifica el nombre del producto y la comuna 👍 

SC enviada:

**Comment by felipedonoso** [comment]
Se revisa el reporte de un proyecto de una SC enviada:

![image](https://user-images.githubusercontent.com/5757157/28026675-c5427494-6564-11e7-8fa0-33f6c19eb13d.png)

Aprobando la SC:

![image](https://user-images.githubusercontent.com/5757157/28026730-f6c829d2-6564-11e7-8518-2a41e95015c1.png)

![image](https://user-images.githubusercontent.com/5757157/28026776-16034228-6565-11e7-9758-6a85e8413987.png)

**Comment by felipedonoso** [comment]
Revisando el reporte en Administración:

Ahora se puede visualizar los cambios reflejados:

![image](https://user-images.githubusercontent.com/5757157/28026881-56c61812-6565-11e7-8608-1c1aa6c26220.png)

Creando una nueva SC:

Se cambia el nombre y la comuna de Cerrillos a Cerro navia.

Se sigue mostrando el nombre del producto el último que fue aprobado.

![image](https://user-images.githubusercontent.com/5757157/28028147-8fcc7fbc-6569-11e7-9ceb-dd2a5d54cd47.png)

Al Rechaza la SC:

![image](https://user-images.githubusercontent.com/5757157/28028219-d61e885c-6569-11e7-8762-75efb69759c7.png)

![image](https://user-images.githubusercontent.com/5757157/28028252-eed0560a-6569-11e7-8d83-70d10261c3dc.png)

**Comment by felipedonoso** [comment]
@pabloespinoza  estaría listo para pasar a producción en conjunto con los otros cambios ya revisados previamente.

**Comment by felipedonoso** [comment]
@pabloespinoza, este es el código de proyecto: 

1700042041 | Proyecto GRILLA SC

Para mayor información:

https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/25

**Comment by felipedonoso** [comment]
@pabloespinoza, la grilla esta OK, solamente el reporte al momento de enviar una SC no carga.

REVISANDO ADMINISTRACIÓN:

![image](https://user-images.githubusercontent.com/5757157/28072685-bdefc1f2-6621-11e7-86ba-237f763950f0.png)

PRESIONANDO EL REPORTE: No carga el reporte.

![image](https://user-images.githubusercontent.com/5757157/28072759-fb9477b4-6621-11e7-95a3-1bcd5f8fbc23.png)


**1700042018 | Prueba reporte -MODIFICANDO EL NOMBRE 12345**

**Comment by felipedonoso** [comment]
@pabloespinoza, el reporte esta OK, al igual que la grilla pero al momento de aprobar la SC aparece la franja azul sin el mensaje, el proyecto es: **1700042018**

**Comment by felipedonoso** [comment]
@pabloespinoza, como lo conversamos en el tema del mes de inicio de un producto, cuando se crear una SC, deberá permitir seleccionar desde el mes actual en adelante, ahora bien si ese mes es menor al mes de inicio del proyecto original, debería tomar el mes original del proyecto en adelante.

**Comment by felipedonoso** [comment]
@pabloespinoza, estaría listo para pasar a PRODUCCIÓN, con el mes de inicio habilitado y que tomará el mes de inicio del proyecto como tope inferior.

Favor de dejar todo listo para pasar a producción y hacer su revisión  en producción.

**Comment by felipedonoso** [comment]
@pabloespinoza, como lo habíamos conversado habría que agregar los botones que se despliegan en la revisión de una SC, en la bandeja de entrada. Para todos los demás perfiles.

La tarea asociada es la siguiente:

https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/26

**Comment by felipedonoso** [comment]
@pabloespinoza, mira por favor este caso: Es una sc del proyecto 1700042222, se han creado varias Sc para el mismo producto 1.

![image](https://user-images.githubusercontent.com/5757157/31770919-66f85bb0-b4b0-11e7-9e45-add522684ba7.png)

**Comment by felipedonoso** [comment]
Conclusión:

Se cierra esta tarea, debido al poco compromiso por parte del Departamento del Alto Rendimiento
