### ISSUE TITLE
Actualizar la franja de colores en el listado de Beneficiario.

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#32]

**Comment by felipedonoso** [comment]
Se debe considerar al Beneficiario como "POR OBJETIVO" a este no se le debe exigir el horario.

**Comment by pabloespinoza** [comment]
Publicado en QA.

**Comment by felipedonoso** [comment]
@pabloespinoza , me mando un error al asignar un nuevo beneficiario:
![image](https://user-images.githubusercontent.com/5757157/35392252-18177c9e-01c0-11e8-982f-51de0e36f071.png)


Proyecto: Actualizar la franja de colores en el listado de Beneficiario. #32

**Comment by felipedonoso** [comment]
### Ingresando un gasto por OBJETIVO, con Geolocalización sin Horario:

![image](https://user-images.githubusercontent.com/5757157/35395285-b4f5de2c-01c8-11e8-93ec-2202591c0feb.png)

**Geolocalización Agregado:**

![image](https://user-images.githubusercontent.com/5757157/35395327-d3195582-01c8-11e8-998c-6989cbe148bc.png)

**Sin Horario registrado:**

![image](https://user-images.githubusercontent.com/5757157/35395362-e84dcd98-01c8-11e8-9446-d349f172d43f.png)

**Al seleccionar Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35396183-f78a7bd8-01ca-11e8-948d-58e96ef7acf2.png)

**Comment by felipedonoso** [comment]
### Ingresando gasto por Objetivo, sin Geolocalización ni horario

![image](https://user-images.githubusercontent.com/5757157/35396289-35d0e0bc-01cb-11e8-8d3d-c7d4efc0ad80.png)

**Ahora en Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35396333-50967826-01cb-11e8-92f0-05db74ac211f.png)

**Ver detalle:**

Se le agrego la geolocalización, y funciono perfecto.

![image](https://user-images.githubusercontent.com/5757157/35396430-8ee4c114-01cb-11e8-9077-8f0ae0c0a387.png)

**Comment by felipedonoso** [comment]
### Realizando un gasto en Viáticos:

![image](https://user-images.githubusercontent.com/5757157/35396550-d12dff86-01cb-11e8-8703-5b03534de2b9.png)

**Se agrega el gasto en viáticos:**

![image](https://user-images.githubusercontent.com/5757157/35396644-07263d88-01cc-11e8-80ef-aeca1a4af160.png)

**La franja debería pasar a color VERDE:**

![image](https://user-images.githubusercontent.com/5757157/35397098-5336d6be-01cd-11e8-9871-159579d9fb99.png)

**Comment by felipedonoso** [comment]
@pabloespinoza para el caso anterior, ejemplo si una persona solamente se le pagará el viático, este beneficiario al momento de estar asociado al gasto debería estar con una franja **verde**.

**Comment by felipedonoso** [comment]
Al revisar se puede observar que la franja esta de color verde:

![image](https://user-images.githubusercontent.com/5757157/35405357-a789d92a-01e4-11e8-8081-6abc403fe2ec.png)

Se creará  un nuevo gasto:

![image](https://user-images.githubusercontent.com/5757157/35405381-bd2603ee-01e4-11e8-976c-bb0d6114c4e4.png)

Al guardar un gasto en Alimentación y hospedaje, no permite grabar:

![image](https://user-images.githubusercontent.com/5757157/35405574-55c13da8-01e5-11e8-8856-bd8f5ebda0ac.png)


@pabloespinoza, al crear un nuevo producto, e ingresar un nuevo beneficiario, a este no se le puede asignar un gasto en Alimentación y Hospedaje. Al presionar Guardar queda estático sin dar una respuesta.

**Comment by felipedonoso** [comment]
El problema detectado anteriormente se debe al log de la base de datos de QA.

![image](https://user-images.githubusercontent.com/5757157/35443344-85a3d13a-0289-11e8-9694-070916d86b5a.png)

Entonces ahora la franja deberá estar en color Verde:

![image](https://user-images.githubusercontent.com/5757157/35443371-9b7e3eaa-0289-11e8-83ea-d21f10996ec4.png)

**Verfiicar y postular**

![image](https://user-images.githubusercontent.com/5757157/35443443-d7945e1a-0289-11e8-858f-89ac81624b3e.png)

**Revisando el detalle:**

![image](https://user-images.githubusercontent.com/5757157/35443468-ef2b4714-0289-11e8-81f0-3c63538ac984.png)

**Comment by felipedonoso** [comment]
**Revisando los Beneficiarios sin gastos:**

![image](https://user-images.githubusercontent.com/5757157/35443883-5dc69af6-028b-11e8-9e6f-0dba3fc7f798.png)

Al revisar en el listado del producto **Actualizar la franja de colores en el listado de Beneficiario. #32** se observa quién tiene la franja roja o no tiene gastos asociados es:

![image](https://user-images.githubusercontent.com/5757157/35443951-a3e0a8e2-028b-11e8-8f8f-527f94f17d5a.png)

Por otra parte en el producto Producto **Validando ALIMENTACIÓN Y HOSPEDAJE**, no hay gasto en personal que este con la franja roja:

![image](https://user-images.githubusercontent.com/5757157/35444035-efbc1bb6-028b-11e8-9faf-9e67ce0d1c33.png)

**Y en el Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35444089-261ef688-028c-11e8-8d16-7d064bbfa910.png)

@pabloespinoza, en la opción Verificar y postular, solamente debería aparecer:

![image](https://user-images.githubusercontent.com/5757157/35444454-60c93590-028d-11e8-9d3f-9ef3f40e4487.png)

Del producto: **Producto Actualizar la franja de colores en el listado de Beneficiario. #32**

**Comment by felipedonoso** [comment]
Revisando el proyecto:

Solamente tenemos un beneficiario sin gastos asociados:

**Producto**: 
Actualizar la franja de colores en el listado de Beneficiario. #32
**Beneficiario**:  
PAULA ALEJANDRA | CASTRO | REYES | TÉCNICO/ENTRENADOR

Al Verificar y postular se presenta el problema:

El sistema encuentra que hay un beneficiario sin gastos asociados:

![image](https://user-images.githubusercontent.com/5757157/35512999-5950d8ae-04e0-11e8-89b3-0444c9587da5.png)


**Revisando el botón VER DETALLE: Ahora se visualiza el beneficiario incompleto en su gasto:**

![image](https://user-images.githubusercontent.com/5757157/35513069-975303b6-04e0-11e8-9c5b-6655ee7be6b7.png)

 Agregando el gasto desde la opción **VER DETALLE:**

![image](https://user-images.githubusercontent.com/5757157/35513128-c82b1b9a-04e0-11e8-943b-b6be1f86a9e5.png)

Ahora al Verificar y postular debería exigir la **Geolocalización**:

![image](https://user-images.githubusercontent.com/5757157/35513163-e828eea4-04e0-11e8-8da4-f29a80eff396.png)

Ingresando la _**Geolocalización:**_

![image](https://user-images.githubusercontent.com/5757157/35513232-22efa6a4-04e1-11e8-83af-2664efd46dcd.png)

Por último el proyecto estaría listo para poder ser POSTULADO/INGRESADO:

![image](https://user-images.githubusercontent.com/5757157/35513291-52b9d850-04e1-11e8-814c-8d0c55e7710c.png)

**Comment by felipedonoso** [comment]
Se creará un nuevo beneficiario sin la opción de estar por Objetivo y debería exigir el **HORARIO**:

Producto: **Validando ALIMENTACIÓN Y HOSPEDAJE**

Beneficiario: **POR DEFINIR**

![image](https://user-images.githubusercontent.com/5757157/35516614-f54fe970-04ea-11e8-872e-2b593fa97509.png)

Estaría sin OBJETIVO:

**Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35516707-3df36134-04eb-11e8-8c5a-81e542c3501d.png)

Revisando el Detalle **Geolocalización**:

Se crea pero no se agrega **HORARIO**:

![image](https://user-images.githubusercontent.com/5757157/35516821-811ce750-04eb-11e8-925b-f2bb4e5e32aa.png)

**Verificar y postular:** Debería salir con problemas:

![image](https://user-images.githubusercontent.com/5757157/35516868-a16f0736-04eb-11e8-9b1e-d461d6ed2b1e.png)


Se agrega el **HORARIO**:

![image](https://user-images.githubusercontent.com/5757157/35516949-dfbc46e8-04eb-11e8-8f47-107f8a7d81a8.png)

**Comment by felipedonoso** [comment]
@pabloespinoza estaría OK, favor de dejar listo para pasar a producción.

**Comment by felipedonoso** [comment]
Se vuelve abrir la tarea, 

@pabloespinoza se me paso el tema por #DEPORTISTAS, al ser deportistas no debería exigir horario tampoco ya que no recibe #REMUNERACIÓN.

**Comment by felipedonoso** [comment]
Se revisará en QA, el gasto en DEPORTISTA, para ver si es un problema de código o de publicación.

Proyecto: #Actualizar la franja de colores en el listado de Beneficiario. #32
Producto: Actualizar la franja de colores en el listado de Beneficiario. #32

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/ffd23190-24bd-486e-8bd8-92031e5eb585)

Verificar y postular:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/c1c45218-b210-4522-8a36-8a37b99ce232)

Conclusión:

Hay que revisar la publicación, ya que en QA valida que el deportista no EXIJA el HORARIO.

**Comment by felipedonoso** [comment]
### Se agrega un beneficiario no DEPORTISTA y son gastos en REMUNERACIÓN. Si se le agrega un gasto en bienes y servicios, no debería exigir HORARIO a dicha persona.

Producto: **Validando ALIMENTACIÓN Y HOSPEDAJE**
Beneficiario: 

![image](https://user-images.githubusercontent.com/5757157/35569105-ee819304-05a9-11e8-8c05-3d546780ed87.png)

![image](https://user-images.githubusercontent.com/5757157/35569137-032a5138-05aa-11e8-8ae8-f91fe372c099.png)

**Gasto en Alimentación y Alojamiento:**

![image](https://user-images.githubusercontent.com/5757157/35569180-34c2f718-05aa-11e8-8ce0-ffcb8934d574.png)

Al revisar en la grilla de BENEFICIARIOS, se puede observar que esta correcto con la franja de color VERDE:

![image](https://user-images.githubusercontent.com/5757157/35569228-68fde5ba-05aa-11e8-897b-4fe381793274.png)

**Ahora al VERIFICAR y POSTULAR:**

![image](https://user-images.githubusercontent.com/5757157/35569618-58ae0b3a-05ab-11e8-99eb-a051c40f7a48.png)

**Comment by felipedonoso** [comment]
Se harán las siguientes validaciones, al cambiar en true la variable SW en la función Validar y postular:

1. Crear producto sin gastos
2. Solamente Deportistas simulando el proyecto de Ajedrez


**Crear producto sin gastos:**

![image](https://user-images.githubusercontent.com/5757157/35571223-3e840278-05b0-11e8-8192-545ed1085712.png)

**VERIFICAR Y POSTULAR: OK**

![image](https://user-images.githubusercontent.com/5757157/35571317-8314f546-05b0-11e8-9796-3420b9454f77.png)

**Solamente Deportistas simulando el proyecto de Ajedrez:**

![image](https://user-images.githubusercontent.com/5757157/35571449-ebb9e48a-05b0-11e8-99cd-024dbef34e37.png)

**Se crea el gasto en Bienes y servicios:**

![image](https://user-images.githubusercontent.com/5757157/35572072-923ab6bc-05b2-11e8-9d97-b983efeaf560.png)

### Verificar y postular:

![image](https://user-images.githubusercontent.com/5757157/35572121-b5f85348-05b2-11e8-95be-9331a5f8e1dc.png)


### La revisión estaría ok.

**Comment by felipedonoso** [comment]
### Revisión por OBJETIVO:

![image](https://user-images.githubusercontent.com/5757157/35572228-f23b9f0e-05b2-11e8-8b19-2248191c769a.png)

**Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35572291-0e4ef45c-05b3-11e8-9809-c8b5e5e0956f.png)

**Se crea el gasto:**

![image](https://user-images.githubusercontent.com/5757157/35572372-3cd5c030-05b3-11e8-8ed3-57de2d180726.png)

**Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35572420-5741e0ac-05b3-11e8-9586-d7d56dbee3d7.png)

**Ver detalle:**

![image](https://user-images.githubusercontent.com/5757157/35572512-82610c72-05b3-11e8-8971-b3e0754c7d1e.png)

**Se asigna solamente GEOLOCALIZACIÓN:**

![image](https://user-images.githubusercontent.com/5757157/35572564-a2eb0a92-05b3-11e8-8746-d0b188489d90.png)

**Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35573107-d96ba8f0-05b4-11e8-8ee6-348e3651695b.png)


Al revisar el producto: Crear producto sin gastos

![image](https://user-images.githubusercontent.com/5757157/35573235-431572ae-05b5-11e8-948d-800ef28a5e59.png)


# Conclusión:

**Estaría todo OK, y debería pasarse a producción con el cambio del valor de la variable en valor true.**

**Comment by felipedonoso** [comment]
### Revisando en Producción:

Proyecto: **Validación del horario en Gasto en personal#35**

**Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35582830-c23af626-05ce-11e8-98ae-d9d60f5b85fb.png)

Revisando  los productos: **Producto Horario - Asignar Beneficiario**

![image](https://user-images.githubusercontent.com/5757157/35583065-70c8ac56-05cf-11e8-8dbb-cc83ee9544c5.png)

Asignando el Horario:

![image](https://user-images.githubusercontent.com/5757157/35583160-c1358344-05cf-11e8-9170-b07ef57555d0.png)

**Verificar y postular:**

![image](https://user-images.githubusercontent.com/5757157/35583194-dd668004-05cf-11e8-810b-7180d0c11b02.png)

**Ahora se eliminará el horario:**

![image](https://user-images.githubusercontent.com/5757157/35583248-0b91008a-05d0-11e8-8dc8-98cd26efa35b.png)

Verificar y postular:

![image](https://user-images.githubusercontent.com/5757157/35583278-24c007ea-05d0-11e8-867c-9e4adaf3a23d.png)

Ahora se modificará el gasto por **OBJETIVO**:

![image](https://user-images.githubusercontent.com/5757157/35583376-836d12d8-05d0-11e8-8b1b-06ee65c0e3ef.png)

La validación por el gasto en personal por OBJETIVO, se encuentra

**Comment by felipedonoso** [comment]
Se ingresarán solamente DEPORTISTAS:

![image](https://user-images.githubusercontent.com/5757157/35585280-4a9d701e-05d6-11e8-951b-8a0545ffcc3f.png)

Se crea el gasto en Alimentación y Alojamiento:

![image](https://user-images.githubusercontent.com/5757157/35585452-ae636fd6-05d6-11e8-9191-45c9e6855c27.png)

**Comment by felipedonoso** [comment]
@pabloespinoza   , en el sistema de postulación al momento de crear un gasto "Asignaciones Especiales", en este caso también es una excepción y no debería pedir Geolocoalziación ni horario.

**Comment by felipedonoso** [comment]
@pabloespinoza  como mencionaste esto estaba considerado para los Deportistas, se hará la consulta en la reunión :

https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/issues/62

**Comment by felipedonoso** [comment]
# Se cierra esta tarea ya que las asignaciones especiales es solamente para DEPORTISTAS.
