### ISSUE TITLE
Cambio de horario de una actividad

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#4]
Esta tarea solo contempla, la modificación de la jornada de un gasto en personal y un gasto en Bienes y servicios.

1. Modificar el horario: Cambiar solamente el horario, ej: si dice de 08:00 am a 17:00 hrs, que sea de 09:00 hrs a 18:00 hrs.
2. Modificar Horario:  Cambiar los días de la actividad, por Ej: si dice de Lun a Vie, dejar Lun-Mar_Vier.

**Tomar: en cuenta que los proyectos deben estar en estado APROBADO.**

### Credenciales:

http://10.15.1.51/AltoRendimientoQA
RUT:16645373
Clave:federacion2016

**Comment by danteghirardelli** [comment]
Browser: Mozilla Firefox
Proyecto 1700042998 - Nombre "Sao Paulo" del periodo 2016

![image](https://cloud.githubusercontent.com/assets/21196249/24358334/357cb458-12d7-11e7-97e8-ad343581c89b.png)
Como QA no me compete dar sugerencias pero esta vez si lo haré.
Sería bueno eliminar las imágenes en portada. Esto porque ocupa demasiado espacio y hace que se pierda el botón de ingreso a la aplicación.
![image](https://cloud.githubusercontent.com/assets/21196249/24358595/07ee7ae8-12d8-11e7-99df-ea625d436b3e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24359921/282c73d8-12dc-11e7-9162-92882fedfce3.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24360039/7d93077e-12dc-11e7-868b-93c24370daa0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24360083/b09df0ca-12dc-11e7-83a5-a9e5e046598f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24360408/a68e84fe-12dd-11e7-8bf6-8ed38d0256fd.png)

En "Acciones" icono Editar no aparece claro.

![image](https://cloud.githubusercontent.com/assets/21196249/24360707/7ddb6d96-12de-11e7-88f7-2130f7f727c3.png)

Se modificará el horario de inicio y días de la semana.

Observación:
Se pierden los botones "Cancelar" y "Guardar".

![image](https://cloud.githubusercontent.com/assets/21196249/24360913/fab51524-12de-11e7-96f2-b31793146be1.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24361573/a4d8b47e-12e0-11e7-9a52-dbbafa0b8f6b.png)

Se modifica Fecha Inicio y Fin al año en curso/2017
![image](https://cloud.githubusercontent.com/assets/21196249/24361588/b14b75f2-12e0-11e7-8e5a-cab5df468248.png)

Sistema no realiza la acción y mantiene el mensaje “La fecha no puede ser inferior a la fecha de inicio del producto”.

Estimados, consultar con el Usuario para determinar si está bien o no el que no realice la acción.

**Comment by danteghirardelli** [comment]
Browser: Mozilla Firefox
Proyecto 1700042017 - Nombre "Preba Solicitud Cambio 1 " del periodo 2017
![image](https://cloud.githubusercontent.com/assets/21196249/24363842/6665c4e6-12e7-11e7-89b7-66800921c8c8.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24364925/a250f522-12ea-11e7-82a1-988fb59f5afc.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24364934/a7719994-12ea-11e7-8cff-7a75111bb10e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24365339/fb4adbc4-12eb-11e7-8209-9539a71642f1.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24365547/aff2b8d0-12ec-11e7-90d4-028cd21838e1.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24365584/d61ebda6-12ec-11e7-8e76-bf854a44c71f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24366486/a3dec81a-12ef-11e7-9515-04fec66f8df9.png)

Se modifica la Comuna.
![image](https://cloud.githubusercontent.com/assets/21196249/24366990/57e08c9e-12f1-11e7-9091-0cdf65444207.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24367118/d3528f4e-12f1-11e7-9092-da31ab37f879.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24367132/dd17da20-12f1-11e7-9f94-46edcc5a6bf7.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24367320/9739529e-12f2-11e7-8f40-6a1a6767146b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24367484/2cf2cfd6-12f3-11e7-91ef-293eb028b8f4.png)


![image](https://cloud.githubusercontent.com/assets/21196249/24367636/bc093a3e-12f3-11e7-8796-e0debc93be91.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24371643/d9a710da-1301-11e7-8993-71442b0c4b87.png)


-----------------------------------------------------------------------------------------------------
INDE 12
http://10.15.1.51/AdministracionQA 
RUT: 153149682
Clave: Nov0915,

Browser: Mozilla Firefox
Proyecto 1700042017 - Nombre "Preba Solicitud Cambio 1 " del periodo 2017

![image](https://cloud.githubusercontent.com/assets/21196249/24372758/63d2fd70-1305-11e7-976e-06f15f79c002.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24373027/5d7fca1a-1306-11e7-9ebb-5c31a4b5d745.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24373825/09e7e9ac-1309-11e7-9cb1-bde5d185bb02.png)


Esta prueba quedará STBY hasta el aviso del Cliente.

**Comment by danteghirardelli** [comment]
INDE 12

![image](https://cloud.githubusercontent.com/assets/21196249/24404547/5f50a3c2-1398-11e7-83b5-c3d9df1ebdda.png)

No permite ingresar con Usuario 153149682/Nov0915,

**Comment by danteghirardelli** [comment]
INDE 11

Browser: Mozilla Firefox
Proyecto 1700042997 - Nombre "Revisión Plurianual 2017 " del periodo 2017



![image](https://cloud.githubusercontent.com/assets/21196249/24406859/b811d042-139f-11e7-8e48-99e19018ef64.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24408750/e34b7128-13a4-11e7-9410-8cd7f9f6b2bf.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24409099/983bfb16-13a5-11e7-8e53-fb90b59d14ba.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24409268/1c606058-13a6-11e7-83d2-72fe536e15a3.png)

-------------------------------------------------------------------------------------------------------------------
## INDE 12
![image](https://cloud.githubusercontent.com/assets/21196249/24409664/44d9fba6-13a7-11e7-96fb-8a4195a4aa41.png)
Pablo ahora se puede ingresar.
-------------------------------------------------------------------------------------------------------------------
...continuación.

![image](https://cloud.githubusercontent.com/assets/21196249/24411065/4082d178-13ab-11e7-9f57-ef2474f94b5c.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24411079/4cd2a714-13ab-11e7-8901-0b4db87adf67.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24411387/258e268c-13ac-11e7-9137-5fd936c30b3c.png)

Se modifica el tipo de Gasto.
![image](https://cloud.githubusercontent.com/assets/21196249/24411802/1a3e10ac-13ad-11e7-9c4a-06e552822113.png)





Sistema indica "The value "Infinity" is not valid for bga Total".
¿Por qué da este mensaje?

**Comment by danteghirardelli** [comment]
![image](https://cloud.githubusercontent.com/assets/21196249/24413276/59ce0aca-13b1-11e7-9b33-0f74783acf76.png)

**Comment by felipedonoso** [comment]
Grande The King of King 
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 :1st_place_medal:

**Comment by danteghirardelli** [comment]
Proyecto --> The King 23
![image](https://cloud.githubusercontent.com/assets/21196249/24463765/181cda8e-147e-11e7-8d32-5c0d486e45c6.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24463824/4737bd98-147e-11e7-91d4-443dbb2221ac.png)


![image](https://cloud.githubusercontent.com/assets/21196249/24463917/983b70c2-147e-11e7-9627-9a425caedf1b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24464031/01a765b6-147f-11e7-8ac9-6495dc851b6d.png)

Se pierden los botones "Cancelar" y "Guardar" por barra informativa.

**Comment by danteghirardelli** [comment]
![image](https://cloud.githubusercontent.com/assets/21196249/24464422/2c0fa2ae-1480-11e7-8b7b-375c07301b21.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24464455/54486b8e-1480-11e7-9bdc-fbd737e045c9.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24470748/6165b572-1496-11e7-9896-cca5c39d08fa.png)

Mejora realizada.

Ahora el Pop Up de "Nuevo Gasto" aparece sobre el footer(pie de página).

Gracias Pablo.

Esperemos la opinión del Cliente.

**Comment by danteghirardelli** [comment]
![image](https://cloud.githubusercontent.com/assets/21196249/24502848/eb4c8448-1525-11e7-992e-64392dd66351.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24502855/f0e6f65e-1525-11e7-9a19-27a7b3e64771.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24502860/f83403b6-1525-11e7-9ef7-5c830332cc69.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24502898/31332e30-1526-11e7-8ced-0b258fdb59f3.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24503168/4a92c4e8-1527-11e7-8fe9-9dea5be6c8b8.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24505248/9694cae6-152f-11e7-9cd4-aad368664487.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24505468/5ea5989e-1530-11e7-82a5-f2cc0ccdc02d.png)

Nuevo Producto 
![image](https://cloud.githubusercontent.com/assets/21196249/24506452/f003c556-1533-11e7-88c6-038dc7cbdcee.png)

STBY(por otro proyecto a revisar)

**Comment by danteghirardelli** [comment]
Proyecto-->
Plan de Desarrollo Administrativo 2017 –Replica
![image](https://cloud.githubusercontent.com/assets/21196249/24508533/140dab00-153a-11e7-978b-6c8407b5001e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24508601/4c78c434-153a-11e7-92a1-34a8bdea3c0e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24508646/7afd8f88-153a-11e7-8785-45fe0eebdfa3.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24508767/defcb838-153a-11e7-96b8-aa36e23f2bfa.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24508818/0cccfe62-153b-11e7-9aa2-6aa5ac000319.png)
 
![imagen](https://cloud.githubusercontent.com/assets/21196249/24509921/b131d53c-1535-11e7-84db-1d73c6978912.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24509929/b7890086-1535-11e7-97c7-90e5d5eeada3.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24509933/be146c56-1535-11e7-8180-37257f4b0850.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24511114/1489df82-1539-11e7-8cfb-d6de9c9cec92.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24511166/38812f1c-1539-11e7-987d-52aff245a4fc.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24511312/b41836ac-1539-11e7-8b0e-9468d63cffc5.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24511446/162fe664-153a-11e7-8894-8ef5f9228e23.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24511658/51c7cf5c-153a-11e7-8310-b0b51311a849.png)

Nuevo Gasto de Administración

![imagen](https://cloud.githubusercontent.com/assets/21196249/24520381/44d53746-1556-11e7-83be-1c13d60d1c9d.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24520386/4b7c3b76-1556-11e7-93d4-fa5f4306369c.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24520393/503d10b8-1556-11e7-9495-f0430195f037.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24520401/561a1dbe-1556-11e7-965c-0cf99616fc9e.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24520410/5c5b7e20-1556-11e7-8855-9e24390a764e.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24520420/6424aac8-1556-11e7-81fb-f8373155af15.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24520427/6960249a-1556-11e7-84fd-bc3bd0329289.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24520432/6f14ae24-1556-11e7-9af9-52dea5c413ca.png)

Se revisará con el Cliente para ver si necesita agregar productos en el Proyecto.

**Comment by danteghirardelli** [comment]
Verificar y Postular
![imagen](https://cloud.githubusercontent.com/assets/21196249/24521979/1262c656-155c-11e7-8ee2-a5d164051da3.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24522037/3c1a65d0-155c-11e7-8265-cb52ef436e5a.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24522089/6c6d394c-155c-11e7-8526-e585f2ba071a.png)

Se ingresa mas presupuesto a la línea

![imagen](https://cloud.githubusercontent.com/assets/21196249/24523269/7f27c666-1560-11e7-8fe5-d887bb7a73bb.png)

@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
### Ahora revisando desde la Administración:

![image](https://cloud.githubusercontent.com/assets/5757157/24523346/24e35d06-1569-11e7-9a1c-841d51277ced.png)

**Aceptando el proyecto(Ex Preselección):**

![image](https://cloud.githubusercontent.com/assets/5757157/24523394/4ae8a52e-1569-11e7-9ccf-9a6c2c04d2a4.png)

![image](https://cloud.githubusercontent.com/assets/5757157/24523446/71be10b2-1569-11e7-907b-4d4293ab499b.png)


@danteghirardelli favor de revisar en la bandeja de entrada que aparezca el icono de v**erificar y postular**

**Comment by danteghirardelli** [comment]
**Se Verifica y Postula Nuevamente**
![imagen](https://cloud.githubusercontent.com/assets/21196249/24523596/87acfb48-1561-11e7-9bdd-9106ec020ec8.png)
![imagen](https://cloud.githubusercontent.com/assets/21196249/24523761/2e925836-1562-11e7-9edd-2e400a1b7879.png)

![imagen](https://cloud.githubusercontent.com/assets/21196249/24523779/3b3d8a74-1562-11e7-8fe0-f3cf71697b1b.png)

Código # 1700042021 Proyecto en Estado “Postulado”
![imagen](https://cloud.githubusercontent.com/assets/21196249/24523805/514fa2ac-1562-11e7-957e-8637ca6c495f.png)
Mañana continuamos con este Proyecto

@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
Se preselecciona el proyecto;

![image](https://cloud.githubusercontent.com/assets/5757157/24550195/68f218e0-15f3-11e7-96a3-7f384bb25647.png)

@danteghirardelli , favor de crear la SC, como aparece en el documento que te envíe

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Estimado Felipe,
Le ruego colocar mas atención en sus peticiones.
Según negocio para realizar una SC el proyecto debe estar en estado "Aprobado".
Muchas gracias.

**Comment by danteghirardelli** [comment]
## Código # 1700042021 Proyecto en Estado “Seleccionado”.
![image](https://cloud.githubusercontent.com/assets/21196249/24608160/c21a5c66-184b-11e7-9150-047dbe46feff.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24608166/c8dcd8ee-184b-11e7-877d-390dc6be9452.png)
Corregir esta palabra.
![image](https://cloud.githubusercontent.com/assets/21196249/24608975/3732e128-184f-11e7-9a5e-2d647d79cc27.png)

Evaluar Proyecto Seleccionado.
![image](https://cloud.githubusercontent.com/assets/21196249/24608988/47b6d630-184f-11e7-9283-fb0a5c086e97.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24608993/50731e32-184f-11e7-912c-a7e8b68af102.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24608996/558bfe3e-184f-11e7-99d0-5f62c90bdf20.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24609003/5a9426b8-184f-11e7-860d-33166908a4b0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24609016/6b18c084-184f-11e7-99ed-2fad2258a05d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24609026/72eb060a-184f-11e7-8626-b699a039b428.png)
¿Por qué indica “Ningún archivo seleccion” si se agregó uno .txt?

Estado
![image](https://cloud.githubusercontent.com/assets/21196249/24609143/06351220-1850-11e7-9d53-54c5cebec561.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24609412/215ce072-1851-11e7-8fd1-0aa5c4ea90c7.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24609416/2863ee9c-1851-11e7-8c33-e998265c7735.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24609421/2db55ef8-1851-11e7-9567-1b438fe12bb3.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24609429/32e7693e-1851-11e7-930b-8655268c2b66.png)

Guardar Proyecto antes de la SC.
![image](https://cloud.githubusercontent.com/assets/21196249/24609596/c93806fa-1851-11e7-9993-f31c91218b85.png)

Subo PDF del Proyecyto.
[Proyecto1700042021_AntesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/890033/Proyecto1700042021_AntesSC.pdf)

**Comment by danteghirardelli** [comment]
Antes de la SC
![image](https://cloud.githubusercontent.com/assets/21196249/24610655/c254bcbc-1855-11e7-9fe4-65f87c1b8c43.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24610660/c7e968d0-1855-11e7-97e9-767304de1eb3.png)

Generar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/24610837/78248c52-1856-11e7-970b-0f23b2985c46.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24613482/d462163a-185e-11e7-958b-8e052ab60158.png)

Listado de Producto
![image](https://cloud.githubusercontent.com/assets/21196249/24613532/f716996c-185e-11e7-8964-e00d5c0325e9.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24613543/fdae8ce4-185e-11e7-988d-39102cb7ba81.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24613555/036e36de-185f-11e7-9488-8f8f20044627.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24613565/0a6fbcdc-185f-11e7-8707-a88c16466e09.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24613574/101a1a10-185f-11e7-9641-479c9776e009.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24613583/173ee1c2-185f-11e7-9a25-56a7cc004fea.png)

**Se editará la SC**
![image](https://cloud.githubusercontent.com/assets/21196249/24614071/847afd1a-1860-11e7-87fd-b3538ba48e2e.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24614643/419e5170-1862-11e7-8010-970188bb1595.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24614652/4688f2a8-1862-11e7-9e8b-a89e235fd6cc.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24614655/4b44d848-1862-11e7-9200-45c945a1d3ff.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24614674/5074cda0-1862-11e7-9fc7-7227bbe823f6.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24615974/2a590cea-1866-11e7-9b20-dceb9e68c782.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24615984/33b4a236-1866-11e7-9e9a-5bfc1fcea418.png)


![image](https://cloud.githubusercontent.com/assets/21196249/24615987/37fed80c-1866-11e7-87da-52984dc0ed2c.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24615991/3d59be0c-1866-11e7-8bed-3f37b0327d66.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24616000/4425f318-1866-11e7-8f13-b651ed0c5dfa.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24616005/48fe6f46-1866-11e7-92f8-73364430499a.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24616016/50b69d26-1866-11e7-8a1c-b7053e0fc7cb.png)

Enviar SC
![image](https://cloud.githubusercontent.com/assets/21196249/24616049/6820f0f6-1866-11e7-9349-83302af2e64b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24616053/6c89fa20-1866-11e7-9574-54f298d4833f.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24616065/72871d7c-1866-11e7-9877-4c44932202d6.png).
Mensaje correcto.

Se Elimina Solicitud Incompleta
![image](https://cloud.githubusercontent.com/assets/21196249/24617216/b75c05fe-1869-11e7-9519-29df927f681b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24617227/bca2ece4-1869-11e7-943c-bc97802b6b47.png)

Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/24617258/cbb0fda2-1869-11e7-9abb-f7a268f373b5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623901/6fe58b84-1880-11e7-887e-dbf4b15e4806.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623908/76c55e2a-1880-11e7-889c-dd6f6d255e10.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623919/80bc32f0-1880-11e7-9f78-67c6ca22d984.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623927/888c1072-1880-11e7-9103-22f97ed92e31.png)

Cambio en Gasto Personal
![image](https://cloud.githubusercontent.com/assets/21196249/24623937/95bccf66-1880-11e7-9fbc-fed0f6e01a4d.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623949/9db61ab0-1880-11e7-9aa0-3dd71f1fca0e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623955/a1f83be4-1880-11e7-88ff-988b91ed9fa2.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623965/a727a4f6-1880-11e7-89ab-2ea6c938188f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24623976/ad587b02-1880-11e7-87b3-53b6f1d646c4.png)

Se envió la Solicitud de Cambio en forma correcta.
![image](https://cloud.githubusercontent.com/assets/21196249/24624607/cabb42b8-1882-11e7-924d-85d690815b74.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24624623/d5318298-1882-11e7-8436-b09ab6502aba.png)

![image](https://cloud.githubusercontent.com/assets/21196249/24624631/da090d4a-1882-11e7-82e7-6b8e23592227.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24624638/dee92d5e-1882-11e7-824e-6bc7cbba728c.png)
![image](https://cloud.githubusercontent.com/assets/21196249/24624648/e6987c3a-1882-11e7-812c-a877cc805aab.png)

Se realizaron los cambios según el ejemplo.
@felipedonoso @pabloespinoza

**Comment by danteghirardelli** [comment]
Subo PDF del Proyecto después de la SC
![image](https://cloud.githubusercontent.com/assets/21196249/24625502/9626f0ee-1885-11e7-882e-048c2642e44f.png)

[Proyecto1700042021_DespuésSC.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/891049/Proyecto1700042021_DespuesSC.pdf)

@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
@danteghirardelli los cambios se realizaron como se esperaba, al revisar el reporte encontramos las siguientes diferencias:

1.- Monto del **proyecto.**
Proyectos antes SC:

![image](https://cloud.githubusercontent.com/assets/5757157/24656442/f40e4818-1918-11e7-822a-ae64bab21111.png)

Proyectos después SC:

![image](https://cloud.githubusercontent.com/assets/5757157/24656483/22cb27c0-1919-11e7-9114-f52ae490f3e5.png)

**2.- Total de cantidad de RRHH:**

De 01 gasto en personal se paso a 02.
![image](https://cloud.githubusercontent.com/assets/5757157/24656542/5fdbdbf0-1919-11e7-9bde-723526d7f8a6.png)

El monto también debe cuadrar, ya que se utilizo el mismo presupuesto: **$ 9.240.000**

**3.- Gastos en Bienes y Servicios.**

En la SC, no se realizo ningún gasto por lo cual debe permanecer el monto **mensual de $ 1.932.000.**
![image](https://cloud.githubusercontent.com/assets/5757157/24656744/02c32436-191a-11e7-9b95-db4b14c2a295.png)

**4.- Resumen del proyecto.**

El total del proyecto debería ser el mismo, **siempre debe cuadrar $28.560.000.**
![image](https://cloud.githubusercontent.com/assets/5757157/24656818/568bb86c-191a-11e7-87a0-246a49009d00.png)

**5.- Gasto en personal - ALDO.**

El cambio se realizo de **Mar** - Dic  A **Abr** - Dic. El monto debe cuadrar.

![image](https://cloud.githubusercontent.com/assets/5757157/24656949/dde833e4-191a-11e7-895e-cd61f8975664.png)

**Al parecer repite el gasto en personal de ALDO.**

**Comment by felipedonoso** [comment]
Se cierra esta tarea ya que se volvió a reutilizar este código y ya no es posible comparar los resultados del reporte con lo mencionado anteriormente.
