### ISSUE TITLE
<Rendiciones de cuentas> Grilla modificaciones

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#49]
Acá se encontrarán todas las tareas necesarias para cumplir con las mejoras de las grilla

Se estudiará la acción **_Historial de Cambios_**

Se filtrarán por los proyectos aprobados con SC en revisión:

![image](https://user-images.githubusercontent.com/5757157/39703203-a18d1fac-51dd-11e8-896c-a23e7ce161e5.png)

## La grilla a modificar es la siguiente:

![image](https://user-images.githubusercontent.com/5757157/39703240-cf04d1f0-51dd-11e8-869c-f5fb6b2a1ec2.png)

## Nuevos campos a considerar:

- [ ] Versión 
- [ ] Fecha 
- [ ] Usuario responsable
- [ ] Documento PDF
- [X] Motivo Federación
- [X] Observación Analista
- [X] Producto (número + nombre)
- [X] Modificación realizada (PDF)

NOTA: Se han agregado 03 campos.

En la columna **Modificación realizada:**

Debe ser un reporte que deberá contener lo siguiente:

- Código del proyecto
- Producto
- Glosa Federación
- Antes - Después

### Versión Anterior:

![image](https://user-images.githubusercontent.com/5757157/39710711-fb36c826-51f3-11e8-9350-30a4fea7f89e.png)

### Propuesta:

![image](https://user-images.githubusercontent.com/5757157/39710666-d728a954-51f3-11e8-8d88-f563b9c76d58.png)

### Al seleccionar Ver más:

![image](https://user-images.githubusercontent.com/5757157/39711244-8a293c2a-51f5-11e8-8767-fa3a706c0c8e.png)

**NOTA:** El tema de las visualizaciones de las modificaciones se descarta para esta mejora.

Falto Agregar el campo **"DETALLE"** este esta asociado a lo que escribe el **Analista** al momento de **aprobar** una solicitud de cambio.

![image](https://user-images.githubusercontent.com/5757157/39762598-70294baa-52b1-11e8-9b41-d24b49f75700.png)

# Se deberá leer de la siguiente manera:

## Parte principal:

Se encontrará el reporte del proyecto Aprobado.

## Parte inferior:

**Modificaciones aceptadas a los distintos productos del proyecto.**
### Se entiende que la última versión es el proyecto como esta actualmente en el sistema.
De no haber versiones, debe aparecer el mensaje:

**Comment by pabloespinoza** [comment]
@felipedonoso el cambio se encuentra publicado en QA.

![image.png](https://images.zenhubusercontent.com/5a674e6e4b5806bc2bc3f1ee/f54ea367-33eb-4dc8-bec0-be25f312eccd)

**Comment by felipedonoso** [comment]
Se tomará un proyecto que ya se encuentre aprobado con SC en revisión: **1800042017**

![image](https://user-images.githubusercontent.com/5757157/40119566-0567665e-58eb-11e8-916e-fb5e28e3d378.png)

**Revisando las modificaciones:**

El tiempo es bastante lento y ocurre un error:

`http://10.15.1.51/AdministracionQA/SolicitudCambio/ResumenSolicitud?idSolicitud=246`

![image](https://user-images.githubusercontent.com/5757157/40119688-507f4cce-58eb-11e8-9b80-2878c82ac444.png)

**Comment by felipedonoso** [comment]
@pabloespinoza  duda, es posible seguir con las pruebas? quede con la duda haré un proyecto nuevo de cero para ver el versionamiento mientras.

**Comment by pabloespinoza** [comment]
@felipedonoso si, la solicitud de cambio de ese proyecto en particular no se puede aprobar, dado que en converges tiene una fecha por default (01/01/00) y al querer convertirla da error.

**Comment by felipedonoso** [comment]
Se creará un nuevo proyecto:

El mes de inicio del proyecto es de Mayo, por ende no debería cargar meses anteriores en el inicio.

Esto a modo de posible mejora.

![image](https://user-images.githubusercontent.com/5757157/40386240-27755986-5dd7-11e8-8a85-7cd84165ca08.png)

El sistema detecta problemas en el sitio de Converges:

No fue posible seguir con la prueba:

![image](https://user-images.githubusercontent.com/5757157/40386421-b20159f6-5dd7-11e8-8cbc-d65e9036ddcf.png)

**Comment by felipedonoso** [comment]
@pabloespinoza al momento de aprobar el proyecto ocurre el siguiente problema:

![image](https://user-images.githubusercontent.com/5757157/40427544-0615f68e-5e6c-11e8-835e-35466b9eacaa.png)

**Nota:** Fue a las 9:30 hrs.

El proyecto es el siguiente: **1800042020**

![image](https://user-images.githubusercontent.com/5757157/40427634-467251c8-5e6c-11e8-8726-3e2fce724fb5.png)

**Comment by felipedonoso** [comment]
Se observa el icono: **Historial solicitudes de cambio**, dejarlo como Solicitudes de cambio echas

![image](https://user-images.githubusercontent.com/5757157/40446518-7dcc6358-5e9d-11e8-895c-f1e672761423.png)

Historial de cambios, **Versiones del proyecto.**

**Modificando el tipo de producto:**

![image](https://user-images.githubusercontent.com/5757157/40446724-37630768-5e9e-11e8-94cc-c07ac2f02fcb.png)

_Producto Actual:_

![image](https://user-images.githubusercontent.com/5757157/40446768-541b0d88-5e9e-11e8-9135-6bf5f6c0b612.png)

**Comment by felipedonoso** [comment]
Al revisar las modificaciones queda la duda con la geolocalización o dirección de la competencia:

Se escribió Surf en Arica y el punto GPS lo coloco cerca de las costas de Arica, entonces hay que ver si eso coincide al buscar en google tal cual y que dirección se obtiene.


![image](https://user-images.githubusercontent.com/5757157/40447517-d78e03f8-5ea0-11e8-9594-ad2337fd9621.png)


![image](https://user-images.githubusercontent.com/5757157/40447586-184f43ac-5ea1-11e8-9006-b08f5d8a0c37.png)

**Comment by felipedonoso** [comment]
# Conclusión:

@pabloespinoza mira en el botón **Historial de cambios**, debería decir: **Versiones del proyecto**.

- Lo otro lo que aparece en Historial de solicitudes de cambio, eso debería estar en la sección Versiones del proyecto.

- Lo otro no se pudo visualizar los reportes del proyecto.

![image](https://user-images.githubusercontent.com/5757157/40447956-230e3108-5ea2-11e8-8e12-4ba64bbe263f.png)

**Comment by pabloespinoza** [comment]
@felipedonoso se corrige error que consiste en cambiar el valor de la variable idSolictudCambio de null a 0 cuando no tiene solicitudes de cambio, en el SP que inserta la version.

**Comment by felipedonoso** [comment]
@pabloespinoza no permite modificar el Horario eso se revisará en otra tarea.

![image](https://user-images.githubusercontent.com/5757157/40667600-8f11672a-6330-11e8-952a-1b9c1976ab58.png)

### Revisando las versiones:

![image](https://user-images.githubusercontent.com/5757157/40667815-0742aa2e-6331-11e8-8ae0-a5284fc06b80.png)

![image](https://user-images.githubusercontent.com/5757157/40667845-1bc1dec0-6331-11e8-9338-9bb7488f5ee4.png)

# CONCLUSIÓN:

@pabloespinoza esta listo para pasarse a producción.
