### ISSUE TITLE
Revisión SC - 1600042108-Cambio del 5% de un gasto a otro

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#5]
Acá se revisará la SC enviada para el proyecto: 1600042108.

**La información de esta SC se encuentra en:**
https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/2

### Resultado esperado:

**Modificación gasto en personal:**
![image](https://cloud.githubusercontent.com/assets/5757157/24357916/aa4a54b8-12d5-11e7-93fe-761b6ef7ed07.png)

### Creación gasto en gasto generales:
![image](https://cloud.githubusercontent.com/assets/5757157/24357941/c46a19e6-12d5-11e7-9e3b-73764063cd7e.png)

Se debería apreciar estos cambios al momento de revisar el proyecto.

**Comment by felipedonoso** [comment]
Lo primero que se observa es que las opciones no aparece el icono para la revisión:

![image](https://cloud.githubusercontent.com/assets/5757157/24358485/a33b8dc0-12d7-11e7-882a-9cff411ca336.png)

Solamente se pueden ver los documentos adjuntos:

**Esto se realizo con el navegador Google Chrome.**

**Comment by felipedonoso** [comment]
Al leer una SC, en el detalle de ítem de gasto no se aprecia información, esto se debe que en la base de datos de QA no se encuentra el proyecto.

**Se aprecia el cambio del gasto en personal:**
![image](https://cloud.githubusercontent.com/assets/5757157/24363022/ea2f4bb0-12e4-11e7-8b4a-903ea06872bb.png)

**Esto se encuentra OK.**

Ahora se revisa el gasto general, este es un gasto nuevo que se realizo con el monto restado en personal.
![image](https://cloud.githubusercontent.com/assets/5757157/24363114/2cd836ca-12e5-11e7-8a6d-3ad2ef35c64c.png)

El proyecto se guarda antes de la aprobación, este corresponde al original sin modificaciones:



**Ahora se han aprobado los cambios:**

**Comment by felipedonoso** [comment]
Al revisar el reporte no es posible visualizarlo ni descargarlo:

![image](https://cloud.githubusercontent.com/assets/5757157/24410001/43e30e94-13a8-11e7-8464-540e1bfd1e35.png)

**Comment by felipedonoso** [comment]
Se adjunta el reporte previa aceptación de la SC:

[Proyecto - 1600042188 (2).pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/876010/Proyecto.-.1600042188.2.pdf)


Aprobado la SC:

![image](https://cloud.githubusercontent.com/assets/5757157/24411231/c4cc2b46-13ab-11e7-8914-5d3fe55d103e.png)


**Revisando el estado en que quedo:**

![image](https://cloud.githubusercontent.com/assets/5757157/24411363/12896dda-13ac-11e7-98a0-f01040552ea5.png)


Nuevo reporte postEvaluación SC:

[Proyecto %2D 1600042188.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/876046/Proyecto.2D.1600042188.pdf)


Duda con el nombre del nuevo archivo:

Proyecto %2D 1600042188.pdf: **¿El "%2D" significa algo especial como segunda versión?**

**Comment by felipedonoso** [comment]
Revisando el reporte:

1. Modificación gasto en personal: Se debería ver una diferencia en el monto y mes del gasto en personal de Aldo Fabián.

1. En el campo monto aparece un error:
2. Los gastos están igual que antes.
3. No aparece el gasto en Bienes y servicios (Gastos Generales).


![image](https://cloud.githubusercontent.com/assets/5757157/24413928/47c45346-13b3-11e7-98b2-2cf2dfc2dad3.png)


Solamente aparece este gasto:

![image](https://cloud.githubusercontent.com/assets/5757157/24421733/8e9d4e3e-13cd-11e7-8100-f6f51b703a93.png)


# Conclusión:

1. El reporte del proyecto no refleja los cambios mencionados anteriormente.
2. El nombre del estado del proyecto, ¿cuál sería según lo que está en la SC?

**Comment by felipedonoso** [comment]
@pabloespinoza al aprobar la SC, no se refleja en los reportes como se en la tarea: **https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/issues/2**

**Comment by pabloespinoza** [comment]
@felipedonoso el proyecto no se está aprobando, ya que no existe en converges, al aprobar el mensaje no es el que debería estar mostrando el cual ya está corregido.

**Comment by felipedonoso** [comment]
# Conclusión:

**Las pruebas asociadas al 5% del costo del proyecto, ya fueron probadas y con resultado esperado.**
