### ISSUE TITLE
<Mejoras SC>Fecha de termino PRODUCTO < 1800042092>

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#59]
Esta tarea nace debido al error encontrado en producción al modificar un producto que originalmente contempla como Categoría = No hay Deportistas. 

Entonces como ahora ingresarán deportistas, se debe modificar la categoría a "Juvenil".

Entonces se observa que el mes de termino aparece "Seleccione", y no el mes de abril que tiene originalmente.

![image](https://user-images.githubusercontent.com/5757157/40079761-eacb5e16-5856-11e8-98d6-047989f69d5b.png)

**Comment by felipedonoso** [comment]
Modificando el proyecto:

Original:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/f27d9f04-871e-4a6b-bc0c-d0a59ae729a6)

Después:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/8de2c1a8-1e56-4eb3-b1d3-3cc3adcc6e29)

NOTA: Se  modifica la categoría y los meses.

**Comment by felipedonoso** [comment]
Ocurre este error:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/cba81386-ceb7-40ea-9519-e596c83b3b96)

Se modifica el gasto en 5.000.000, en vez de colocar 500 mil, puse 5 millones, con eso la alerta que valida cuando se sobrepasa el monto del producto se acciona, previamente se había quitado el ticket de Beneficiario y aparece la alerta también.

Luego al querer modificar el gasto de 5 millones a 500 mil, aparece el error antes mencionado.

Mensaje a mejorar en otra tarea posterior (Delimitado por comas):

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/225ba41a-82a3-4a17-acf6-8b0bb4ee0e04)

**Comment by felipedonoso** [comment]
Revisando las versiones del proyecto:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/28a95f57-da5c-44f1-b542-7420665321fe)

Revisando las modificaciones:

No esta insertando en converges:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/eab3e7eb-ae13-421f-a161-2b456267e9df)

Al momento de Aprobar ocurre un problema en converges:

Indica el error;

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/5ff970b7-fd35-4a4e-b1c2-88fe5f16c87b)

El botón queda inhabilitado y debería indicar ERROR y el mensaje con la franja en color Rojo.

Conclusión:

- Ya es posible modificar los meses de inicio y de termino. Ya se adelantando la fecha o postergandola.
- Al existir un error en converges debe tratar mejor el error.

Se siguiere agregar al texto el mensaje ERROR; glosa que ya tiene y posteriormente vuelva a intentarlo más tarde. También el color de la franja para que el usuario se percate de que hubo un problema.

Por último lo de bloquear el botón, como lo conversamos @pabloespinoza habría que bloquearlo una vez que se aprieta el botón, para que el usuario comprenda que se esta ejecutando la tarea.

**Comment by pabloespinoza** [comment]
Se publica en QA:

- Cambio de color en mensaje de error.
- Se agrega las palabras "ERROR: " y "vuelva a intentarlo más tarde"

**Comment by felipedonoso** [comment]
# Conclusión:

@pabloespinoza    **esta mejora esta lista para ser pasada en producción**
