### ISSUE TITLE
<Mejoras SC> Correos enviados a los Analistas<SC APROBADA>

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#60]
Se revisará el porqué no salieron los correos a las listas creadas al momento de Aprobar una SC.

**Comment by pabloespinoza** [comment]
@felipedonoso , el cambio se encuentra en QA.

**Comment by felipedonoso** [comment]
@pabloespinoza    la lista de rendiciones de cuenta es la siguiente:

# rendicion@ind.cl

Solamente esta el Conrad luego se irán agregando más.

**Comment by felipedonoso** [comment]
@pabloespinoza  respecto a esto solamente tengo la duda con el correo de la lista de rendición de cuentas.
