### ISSUE TITLE
<PRUEBA> Objetar SC

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#76]

**Comment by danteghirardelli** [comment]
### Postulación
![image](https://user-images.githubusercontent.com/21196249/44872748-bd77f180-ac6c-11e8-9005-76af70fc4e43.png)
Se tomará Proyecto(Felipe) en estado "Aprobado"###  N° 1800042029
 Nombre "Le Coq"
![image](https://user-images.githubusercontent.com/21196249/44873942-f9f91c80-ac6f-11e8-957b-cdc5b9ebfb51.png)
### Se rescata Reporte antes del Cambio
[Proyecto - 1800042029.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/2337577/Proyecto.-.1800042029.pdf)
![image](https://user-images.githubusercontent.com/21196249/44874044-46dcf300-ac70-11e8-802f-3a81fd193d61.png)
![image](https://user-images.githubusercontent.com/21196249/44874102-80156300-ac70-11e8-8ed9-6f76b3462499.png)
![image](https://user-images.githubusercontent.com/21196249/44874263-fe720500-ac70-11e8-9142-f4712b20d15e.png)
No se pueden realizar las acciones(Pablo está revisando la causa).
### Se creará nuevo proyecto
![image](https://user-images.githubusercontent.com/21196249/44874474-ac7daf00-ac71-11e8-8749-03c95d01cd99.png)
![image](https://user-images.githubusercontent.com/21196249/44874567-f49cd180-ac71-11e8-9e6a-4a5f536da561.png)
![image](https://user-images.githubusercontent.com/21196249/44874738-83a9e980-ac72-11e8-9588-48609c81304f.png)
![image](https://user-images.githubusercontent.com/21196249/44874756-9ae8d700-ac72-11e8-972d-fc538ce1ea1a.png)
![image](https://user-images.githubusercontent.com/21196249/44874817-bd7af000-ac72-11e8-9b43-a2713e9b891f.png)
![image](https://user-images.githubusercontent.com/21196249/44874864-e0a59f80-ac72-11e8-8d8d-551527914ab5.png)
![image](https://user-images.githubusercontent.com/21196249/44875059-73463e80-ac73-11e8-80a3-cf0e5a06aa4f.png)
![image](https://user-images.githubusercontent.com/21196249/44875085-8c4eef80-ac73-11e8-8b92-a5e731b8541b.png)
![image](https://user-images.githubusercontent.com/21196249/44875136-ae487200-ac73-11e8-812e-55b35ab94fe2.png)
![image](https://user-images.githubusercontent.com/21196249/44875165-c7e9b980-ac73-11e8-8cfb-83b9e578b473.png)
![image](https://user-images.githubusercontent.com/21196249/44875311-2ca51400-ac74-11e8-8c0e-1535946dde6e.png)
![image](https://user-images.githubusercontent.com/21196249/44875346-47778880-ac74-11e8-98ea-d31246124e3f.png)
### Asignación Beneficiario
![image](https://user-images.githubusercontent.com/21196249/44875447-94f3f580-ac74-11e8-8bfc-3e80ef275647.png)
![image](https://user-images.githubusercontent.com/21196249/44875488-b7860e80-ac74-11e8-8cd7-d7cbff33aa79.png)
![image](https://user-images.githubusercontent.com/21196249/44875553-f025e800-ac74-11e8-873c-4f01edc666ca.png)
![image](https://user-images.githubusercontent.com/21196249/44875584-0e8be380-ac75-11e8-94ac-f4557a42c4ef.png)
![image](https://user-images.githubusercontent.com/21196249/44875629-26fbfe00-ac75-11e8-800c-1883e4a97fce.png)
![image](https://user-images.githubusercontent.com/21196249/44875688-4f83f800-ac75-11e8-8b8c-9e44cf3c2ade.png)
![image](https://user-images.githubusercontent.com/21196249/44875777-8fe37600-ac75-11e8-9ff2-49b30a2fa66f.png)
![image](https://user-images.githubusercontent.com/21196249/44875876-c3be9b80-ac75-11e8-9eab-37d0796cfb21.png)
![image](https://user-images.githubusercontent.com/21196249/44875902-d9cc5c00-ac75-11e8-8f65-ad444b43290d.png)
![image](https://user-images.githubusercontent.com/21196249/44875943-f1a3e000-ac75-11e8-996d-e5a3f61d2c88.png)
![image](https://user-images.githubusercontent.com/21196249/44876026-2d3eaa00-ac76-11e8-9625-8436eb322ee6.png)
![image](https://user-images.githubusercontent.com/21196249/44876051-447d9780-ac76-11e8-953e-2a5895875a8f.png)
### Gastos en Bienes y Servicios
![image](https://user-images.githubusercontent.com/21196249/44876230-d5ed0980-ac76-11e8-945d-3178aa906b99.png)
![image](https://user-images.githubusercontent.com/21196249/44876306-151b5a80-ac77-11e8-85d0-1ab2dd8680d9.png)
![image](https://user-images.githubusercontent.com/21196249/44876477-9e329180-ac77-11e8-8997-02043257c095.png)
![image](https://user-images.githubusercontent.com/21196249/44876507-ae4a7100-ac77-11e8-81bd-c8e79c0e6a15.png)
Se continuará con el Proyecto The KING 22
@felipedonoso @pabloespinoza

**Comment by danteghirardelli** [comment]
### Se continua con Proyecto The KING 22
![image](https://user-images.githubusercontent.com/21196249/44876975-f0c07d80-ac78-11e8-886a-0a65f5cb8f69.png)
![image](https://user-images.githubusercontent.com/21196249/44877026-16e61d80-ac79-11e8-98ab-394c955f3cfa.png)
![image](https://user-images.githubusercontent.com/21196249/44877074-354c1900-ac79-11e8-8cef-9abb586498e9.png)
![image](https://user-images.githubusercontent.com/21196249/44877107-4a28ac80-ac79-11e8-9091-dfc72c6c1efa.png)
![image](https://user-images.githubusercontent.com/21196249/44877152-67f61180-ac79-11e8-8390-e9b5e1c7cc89.png)
![image](https://user-images.githubusercontent.com/21196249/44877218-a7246280-ac79-11e8-98fe-073ee7cbab18.png)
![image](https://user-images.githubusercontent.com/21196249/44877264-ccb16c00-ac79-11e8-81ea-1e3fe949d032.png)
![image](https://user-images.githubusercontent.com/21196249/44877287-e2bf2c80-ac79-11e8-9895-3a73ff79505c.png)
![image](https://user-images.githubusercontent.com/21196249/44877351-100bda80-ac7a-11e8-80c9-6bd2ce34b63a.png)
![image](https://user-images.githubusercontent.com/21196249/44877463-71cc4480-ac7a-11e8-8ba7-9930bdb93ba5.png)
### Evaluar Proyecto Ingresado
![image](https://user-images.githubusercontent.com/21196249/44877552-b3f58600-ac7a-11e8-95c1-b13d352c20a1.png)
![image](https://user-images.githubusercontent.com/21196249/44877617-e3a48e00-ac7a-11e8-964b-40fa39341cdc.png)
### Al evaluar Proyecto sistema despliega mensaje:
### DEbes modificar el nombre"ALEXIS le pega al King"
![image](https://user-images.githubusercontent.com/21196249/44877746-4dbd3300-ac7b-11e8-977c-903c0dd3b373.png)
¿Por qué aparece ese mensaje?
@felipedonoso @pabloespinoza 
![image](https://user-images.githubusercontent.com/21196249/44878069-4c403a80-ac7c-11e8-9915-e677e333b0b2.png)
![image](https://user-images.githubusercontent.com/21196249/44878117-6e39bd00-ac7c-11e8-8a7e-995976a994a2.png)
### Postular
![image](https://user-images.githubusercontent.com/21196249/44878252-c07ade00-ac7c-11e8-9a07-987789f56a67.png)
![image](https://user-images.githubusercontent.com/21196249/44878288-d6889e80-ac7c-11e8-9d33-87b3f1867ac1.png)
![image](https://user-images.githubusercontent.com/21196249/44878395-26676580-ac7d-11e8-91cf-f3b41afe2eae.png)
Proyecto en Estado "Postulado"
![image](https://user-images.githubusercontent.com/21196249/44880033-a7286080-ac81-11e8-994d-375dd8eb7373.png)

### Cambiar Proyecto de Ingresado Pre Seleccionado
![image](https://user-images.githubusercontent.com/21196249/44880139-f1a9dd00-ac81-11e8-8eea-dca9741e8e23.png)
![image](https://user-images.githubusercontent.com/21196249/44880176-143bf600-ac82-11e8-9f6f-735db95f0df9.png)
![image](https://user-images.githubusercontent.com/21196249/44880211-3170c480-ac82-11e8-81b0-5f258b0697c3.png)
![image](https://user-images.githubusercontent.com/21196249/44880348-92989800-ac82-11e8-89b8-809ac086a88f.png)
![image](https://user-images.githubusercontent.com/21196249/44880416-c247a000-ac82-11e8-805d-9a104b274949.png)
![image](https://user-images.githubusercontent.com/21196249/44880495-0044c400-ac83-11e8-9f71-f8162c7437f8.png)
![image](https://user-images.githubusercontent.com/21196249/44880564-371ada00-ac83-11e8-8c25-cf58b1930c0d.png)
![image](https://user-images.githubusercontent.com/21196249/44880863-14d58c00-ac84-11e8-9e54-08704044f929.png)
Proyecto N°1800042041 "The KING 22" en estado "Aprobada"
@felipedonoso @pabloespinoza 
### Se continuará con la SC

**Comment by danteghirardelli** [comment]
### Se creará SC para Proyecto N°1800042041
![image](https://user-images.githubusercontent.com/21196249/44881588-96c6b480-ac86-11e8-90ae-6ddc5c3330f5.png)
@felipedonoso @pabloespinoza 
Felipe por favor mañana continuar con la creación de la SC
Muchas gracias.

**Comment by danteghirardelli** [comment]
Reporte antes de la SC
[Proyecto - 1800042041_AntesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/SolictudDeCambio/files/2345822/Proyecto.-.1800042041_AntesSC.pdf)
### Creación de la SC cambio proyecto N° 1800042041
![image](https://user-images.githubusercontent.com/21196249/44989425-370d2980-af64-11e8-831c-c1fe74ef3191.png)
![image](https://user-images.githubusercontent.com/21196249/44991389-3d9e9f80-af6a-11e8-9438-f96bee74350d.png)
### Generar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/44993811-472c0580-af72-11e8-9ea1-6abda35322b1.png)
![image](https://user-images.githubusercontent.com/21196249/44994038-2f08b600-af73-11e8-8639-bea9e978417e.png)
![image](https://user-images.githubusercontent.com/21196249/44994065-49db2a80-af73-11e8-8b61-f5767f9e44dd.png)
![image](https://user-images.githubusercontent.com/21196249/44994104-77c06f00-af73-11e8-8391-798029f6b659.png)
![image](https://user-images.githubusercontent.com/21196249/44994124-94f53d80-af73-11e8-888d-3e1cc550b7c2.png)
![image](https://user-images.githubusercontent.com/21196249/44994215-f87f6b00-af73-11e8-8003-4061d47fd423.png)
![image](https://user-images.githubusercontent.com/21196249/44994244-1fd63800-af74-11e8-80b8-982b3d1a4191.png)
![image](https://user-images.githubusercontent.com/21196249/44994298-63c93d00-af74-11e8-82c2-a3165ab46c0b.png)
### Enviar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/44994347-9d01ad00-af74-11e8-92c4-3977e5937120.png)
![image](https://user-images.githubusercontent.com/21196249/44994416-f2d65500-af74-11e8-8ade-7d5fb5e84463.png)
![image](https://user-images.githubusercontent.com/21196249/44994437-0d103300-af75-11e8-8655-bf2d17f8eadd.png)
![image](https://user-images.githubusercontent.com/21196249/44994466-2ca75b80-af75-11e8-9700-7ec4bb27d9ff.png)
![image](https://user-images.githubusercontent.com/21196249/44994565-91fb4c80-af75-11e8-82f2-d8e413c8c400.png)
@felipedonoso @pabloespinoza 
### Observación
Se modifica En Gastos Bienes y Servicios
--> De Gastos Generales  a Viáticos
Proyecto N°1800042041
Estado "Aprobado/Solicitud de Cambio/ En Revisión"
¿Podemos revisarlo para realizar la objeción al cambio?

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

![image](https://user-images.githubusercontent.com/21196249/44994954-68432500-af77-11e8-859e-81c8c1021300.png)
![image](https://user-images.githubusercontent.com/21196249/44994985-84df5d00-af77-11e8-9ff1-95ba0a8084d3.png)

### Observación
![image](https://user-images.githubusercontent.com/21196249/44995095-edc6d500-af77-11e8-8f69-1ea7e17f53f9.png)
Se pierde Nombre de Proyecto, Número y Gastos.

**Comment by danteghirardelli** [comment]
![image](https://user-images.githubusercontent.com/21196249/44999766-ffb77080-af95-11e8-942f-614ef401ccc0.png)
![image](https://user-images.githubusercontent.com/21196249/44999781-207fc600-af96-11e8-8dd6-1857630d959d.png)
![image](https://user-images.githubusercontent.com/21196249/44999795-3ab9a400-af96-11e8-929a-6b14f392800f.png)
![image](https://user-images.githubusercontent.com/21196249/44999822-75234100-af96-11e8-9584-b30544019321.png)
![image](https://user-images.githubusercontent.com/21196249/44999831-853b2080-af96-11e8-977e-47d75891c549.png)
![image](https://user-images.githubusercontent.com/21196249/44999845-a1d75880-af96-11e8-8dc1-b33b2a0868de.png)
Se objeta la SC
![image](https://user-images.githubusercontent.com/21196249/44999867-c3384480-af96-11e8-9649-2f1fb1491337.png)
![image](https://user-images.githubusercontent.com/21196249/44999922-1dd1a080-af97-11e8-92b6-aae38e0467eb.png)
### En campo Acción desaparecen los íconos de acciones.
@felipedonoso @pabloespinoza

**Comment by pabloespinoza** [comment]
@felipedonoso , @danteghirardelli está corregido y en QA.

**Comment by felipedonoso** [comment]
**Revisando los iconos de acción del producto:**

![image](https://user-images.githubusercontent.com/5757157/46100730-7bc16480-c1a0-11e8-92ca-c14f3a9f4f98.png)

**Se revisará cada icono:**

![image](https://user-images.githubusercontent.com/5757157/46100775-a27f9b00-c1a0-11e8-81d9-8a71e9e69107.png)

**Se observa que el mapa esta correcto:**

![image](https://user-images.githubusercontent.com/5757157/46100822-c0e59680-c1a0-11e8-9c3f-681e4b4044ee.png)

![image](https://user-images.githubusercontent.com/5757157/46100899-f38f8f00-c1a0-11e8-8888-4e49276dca52.png)

**_Se agrega una nueva persona:_**

![image](https://user-images.githubusercontent.com/5757157/46100974-26d21e00-c1a1-11e8-846b-6e3154557f79.png)

### Subiendo un documento que debe visualizarse al momento de ser aprobada la SC

![image](https://user-images.githubusercontent.com/5757157/46101172-a4962980-c1a1-11e8-869c-b36f77d2ddb9.png)

### Se envía la SC

**Comment by felipedonoso** [comment]
@pabloespinoza el error ocurre en el proyecto 1800042041 al enviar la SC no te la permitirá enviar.
