### ISSUE TITLE
<MEJORA> OBJETAR SC

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/SolictudDeCambio#79]
Se creará la opción de Objetar una SC, con el único fin de que una federación, al momento de que el analista objete un SC se podrá modificar solamente lo necesario y con eso evitar eliminar toda la SC.

Esta es una mejora, que no se considero dentro del proyecto.

**Comment by felipedonoso** [comment]
@pabloespinoza de las pruebas realizadas del @danteghirardelli  se encontro lo siguiente:

Al momento de Objetar un proyecto, se vuelve a ingresar en la plataforma de postulación  y se observa que no aparecen los iconos de Acción:

![image](https://user-images.githubusercontent.com/5757157/45000028-e0214780-af97-11e8-87dd-5828d82faf9c.png)

**Comment by pabloespinoza** [comment]
@felipedonoso , @danteghirardelli está corregido y en QA.

**Comment by felipedonoso** [comment]
### Revisando sobre documentos adjuntos en una SC:

![image](https://user-images.githubusercontent.com/5757157/46105723-2475c100-c1ad-11e8-8918-cca5aede5826.png)

**Al aprobar la SC:**

![image](https://user-images.githubusercontent.com/5757157/46105845-7c142c80-c1ad-11e8-82f0-1ca7b5819ad6.png)

![image](https://user-images.githubusercontent.com/5757157/46105877-9221ed00-c1ad-11e8-9dd2-8379967b3831.png)

**Comment by felipedonoso** [comment]
### Ahora se rechazará la SC con los documentos adjuntos:

Se utilizará el proyecto: 1800042042

![image](https://user-images.githubusercontent.com/5757157/46106152-5c313880-c1ae-11e8-9c25-0cc7e6497242.png)

_**Rechazando la SC:**_

![image](https://user-images.githubusercontent.com/5757157/46106202-7cf98e00-c1ae-11e8-80ec-96993f62ef10.png)



![image](https://user-images.githubusercontent.com/5757157/46106285-b6ca9480-c1ae-11e8-9d9c-4c2e9949a3c9.png)


### Revisando los Documentos:

**En otros: Esta ok no se ven los archivos**

![image](https://user-images.githubusercontent.com/5757157/46106376-e1b4e880-c1ae-11e8-9f26-0c8b18f7e7bb.png)

**Acreditar saldo:**

![image](https://user-images.githubusercontent.com/5757157/46106422-fc875d00-c1ae-11e8-96f9-3b17612d20a3.png)

@pabloespinoza el resultado esta OK:

**_NOTA: Solamente falta revisar en la tabla si se elimino fisicamente el archivo ya que consumiría espacio innecesario._**

**Comment by felipedonoso** [comment]
**Se revisa en la Base de datos y no hay problemas el archivo quedo eliminado:**

```
select * from proyecto where proFolioProyecto=201800042042
select * from solicitud_cambio where idproyecto=10475
select *   from archivo_solicitud_cambio where idSolicitudCambio in(305)
```

**@pabloespinoza esta listo para que se pase a producción**

**Comment by felipedonoso** [comment]
**Mejora al correo ANALISTA:** **RECHAZO**

![image](https://user-images.githubusercontent.com/5757157/46155439-ab7a7600-c24d-11e8-9850-f6f71cfed596.png)

**Al aceptar, la SC:**

![image](https://user-images.githubusercontent.com/5757157/46155632-204db000-c24e-11e8-9106-5d4a74e33bba.png)

**Ahora se Objetará una SC:**

![image](https://user-images.githubusercontent.com/5757157/46167549-70d40600-c26c-11e8-92fb-be369864cfad.png)


**SE REVISARÁ EL CORREO:**

![image](https://user-images.githubusercontent.com/5757157/46167622-ad9ffd00-c26c-11e8-9bcc-20d5e7b8614a.png)


**NOTA**: Solamente habría que cambiar la palabra **Observada** por **OBJETADA**.

Revisando el documento adjuntado que fue Objetado

**En la SC el documento permanece:**

![image](https://user-images.githubusercontent.com/5757157/46167769-125b5780-c26d-11e8-8c88-2f02922a6f00.png)

**Comment by felipedonoso** [comment]
@pabloespinoza estaría listo para ser pasado a producción me avisas cuando este listo.

**Comment by pabloespinoza** [comment]
@felipedonoso las fuentes se encuentran en Git y listas para pasar a produccion.

**Comment by felipedonoso** [comment]
### Se obtiene la versión indicando los siguientes datos:

![image](https://user-images.githubusercontent.com/5757157/46205773-56476e80-c2f8-11e8-8493-b575e4ed8bd9.png)

**_Revisando en producción:_**

![image](https://user-images.githubusercontent.com/5757157/46206581-ceaf2f00-c2fa-11e8-8c14-2b07cb7ba172.png)

Se enviará correo indicando  la mejora a los departamentos involucrados.
